# Generated by Django 5.0.6 on 2024-05-19 14:51

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0002_loan_name'),
    ]

    operations = [
        migrations.RenameField(
            model_name='loan',
            old_name='term_months',
            new_name='term_year',
        ),
    ]
