# Generated by Django 5.0.6 on 2024-05-19 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('loans', '0003_rename_term_months_loan_term_year'),
    ]

    operations = [
        migrations.AddField(
            model_name='loan',
            name='status',
            field=models.CharField(default='Pending', max_length=20),
        ),
    ]
